### ISSUE TITLE
[Feature request] add loaders to modrinth commands

### ISSUE THREAD

**Issue by Arbee4ever** [NotJansel/SkyblockBot#25]
Can you add the loaders to all modrinth commands that have that? I think that's quite an important value to most users.

**Comment by NotJansel** [comment]
I could, if the modrinth api would offer a seperate json element for loaders.
I will ask Emma about this

**Comment by Arbee4ever** [comment]
It does list loaders. But within the "categories" String.

**Comment by NotJansel** [comment]
yes, but I got an answer, that also by getting the versions, they seperately list loaders
edit: i need to figure out how to proceed with projects that seperate loaders tho (f.ex. those who seperate forge and fabric)

**Comment by NotJansel** [comment]
I have figured it all out and it works so far in my beta testing
