### ISSUE TITLE
Modrinth requests need a useragent

### ISSUE THREAD

**Issue by triphora** [NotJansel/SkyblockBot#31]
https://docs.modrinth.com/api-spec/#section/User-Agents

**Comment by NotJansel** [comment]
Thanks for the Issue, I hope it is fine if I have done it this way: [click](https://github.com/HyacinthBots/Allium/blob/develop/src/main/kotlin/org/hyacinthbots/allium/extensions/Modrinth.kt#L49)

**Comment by triphora** [comment]
Yeah that's good
