### ISSUE TITLE
Can't remove channel from log uploading whitelist

### ISSUE THREAD

**Issue by sgmedev** [NotJansel/SkyblockBot#42]
When the code for the add command was copied, the part where it checks if the channel is already in the whitelist wasn't modified. This results in the bot saying that the channel is already in the whitelist and returning early when attempting to remove it and therefore removing channels from the whitelist is impossible, it also says that the channel was removed when it wasn't in the whitelist in the first place. The command description was also not changed.
https://github.com/HyacinthBots/Allium/blob/3fe9e71811b3158c63c044f8ca65e48768dcb3a0/src/main/kotlin/org/hyacinthbots/allium/extensions/LogUploading.kt#L254-L259

**Comment by NotJansel** [comment]
Ah thanks! I will fix that and it will be in the next release as I already did some changes that require something else and it requires some time.

**Comment by NotJansel** [comment]
I will close this when the release comes out.

**Comment by NotJansel** [comment]
new release is out, will close this now
