### ISSUE TITLE
Direct lookup by slug/id

### ISSUE THREAD

**Issue by TheKodeToad** [NotJansel/SkyblockBot#46]
Sometimes searching the slug doesn't have the corresponding project as the first result. it would be convenient if you know the slug like ~~an absolute weirdo~~ me to just go straight to the project.

Considering CurseForge uses /curseforge search maybe Modrinth should do that too and have /[modrinth/curseforge] project be slug/ID based?

Yours very formally (yes)
\- Princess Toadstool

**Comment by NotJansel** [comment]
Thanks for the issue, I will look into it, need some consistency changes in some areas anyways.

**Comment by NotJansel** [comment]
added in 0.6.2, i noted it as slug rn, but ID also may work.
